global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'cloudflare_exporter'
    static_configs:
      - targets: ['cloudflare-exporter:8001'] 
    metrics_path: /metrics
    scheme: http
    scrape_interval: 30s
